### ISSUE TITLE
Failed assertion when running demo apps

### ISSUE THREAD

**Issue by aschuhardt** [eleccoder/raspi-pico-aprs-tnc#1]
Are you able to run the demo apps with the current pico-extras revision?  I'm running into this failed assertion exception when calling the `sendAPRS` method.

The assertion in question can be found [here](https://github.com/raspberrypi/pico-extras/blob/09c64d509f1d7a49ceabde699ed6c74c77e195a1/src/common/pico_audio/include/pico/sample_conversion.h#L261).

Here is my call stack when the assertion fails:

```
__breakpoint@0x10006c28 (c:\Program Files\...\pico-sdk\src\rp2_common\pico_platform\include\pico\platform.h:345)
_exit@0x10006ddc (c:\Program Files\...\pico-sdk\src\rp2_common\pico_runtime\runtime.c:187)
__assert_func@0x10006e88 (c:\Program Files\...\pico-sdk\src\rp2_common\pico_runtime\runtime.c:271)
producer_pool_blocking_give<FmtPWM, FmtS16>@0x100016b2 (c:\Program Files\...\pico-extras\src\common\pico_audio\include\pico\sample_conversion.h:261)
producer_pool_blocking_give_to_pwm_s16@0x10001610 (c:\Program Files\...\pico-extras\src\rp2_common\pico_audio_pwm\sample_encoding.cpp:411)
give_audio_buffer@0x10005fb8 (c:\Program Files\...\pico-extras\src\common\pico_audio\audio.cpp:216)
aprs_pico_renderAudioSamples@0x1000b29c (raspi-pico-aprs-tnc\src\aprs_pico.c:163)
aprs_pico_sendAPRSAudioCallback@0x1000b32e (raspi-pico-aprs-tnc\src\aprs_pico.c:183)
ax25_frame@0x1000bd34 (Unknown Source:0)
ax25_beacon@0x1000b568 (Unknown Source:0)
aprs_pico_sendAPRS@0x1000b42e (raspi-pico-aprs-tnc\src\aprs_pico.c:256)
main@0x10000356 (raspi-pico-aprs-tnc\src\aprs_pico_beacon_demo.c:64)
```

**Comment by eleccoder** [comment]
Hello @aschuhardt, I'm very sorry for not replying sooner. I don't remember to have gotten an email notification ... Anyway, I just tried to build and run the demo program based on the today's master branches of the pico-sdk and pico-extras: The demo was running fine, w/o any exception. So, pls. tell whether your issue still exists or not. Thanks, Thomas

**Comment by eleccoder** [comment]
Closed since no response from the reporter.
